version: '3'

services:
###> doctrine/doctrine-bundle ###
#  php-fpm:
#    image: php:8-alpine
#    container_name: php-fpm
#    volumes:
#      - ./:/symfony
#    ports:
#      - "9000:9000"
#
  base:
    container_name: base
    build:
      dockerfile: ./docker/base/Dockerfile
      context: ./
    links:
      - database
    ports:
      - "9000:9000"
#  base:
#    container_name: base
#    build: ./docker/base
#    links:
#      - database
#    ports:
#      - "9000:9000"
#    volumes:
#      - ./:/symfony
  ngnix:
    container_name: ngnix
    build:
      dockerfile: ./docker/ngnix/Dockerfile
      context: ./
    depends_on:
      - base
    ports:
      - "8081:8080"
    links:
      - base
    volumes:
      - ./docker/ngnix/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/symfony

  database:
    container_name: database
    image: postgres:${POSTGRES_VERSION:-13}-alpine
    user: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ChangeMe}
      POSTGRES_USER: ${POSTGRES_USER:-symfony}
    volumes:
      - db-data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
